#! /usr/bin/env node
const { parse, types, print } = require("recast");
const fsPromise = require("fs/promises");
const minimist = require("minimist");
const validOptions = require("./options");

const DEFAULT_COMMENT = "TODO: function exceeds 50 lines [Generated by Akuma]";
function generateComment(path, line = 50, commentTemplate = DEFAULT_COMMENT) {
  fsPromise
    .open(path)
    .then((filehandle) => filehandle.readFile("utf-8"))
    .then((content) => {
      const ast = parse(content);
      ast.program.body.forEach((declaration) => {
        if (
          declaration.type === "FunctionDeclaration" &&
          declaration.loc.end.line - declaration.loc.start.line - 1 > line
        ) {
          const comment = types.builders.commentLine(
            String.fromCharCode(32) + commentTemplate
          );
          if (declaration.comments) {
            declaration.comments.push(comment);
          } else {
            declaration.comments = [comment];
          }
        }
      });
      return ast;
    })
    .then((res) => {
      fsPromise
        .writeFile(path, print(res).code)
        .then(() => console.log("Done!"));
    })
    .catch((err) => {
      console.log("Generate comments failed\n", err);
    });
}

function checkValidation(options) {
  const properties = Object.keys(options).slice(1);
  function checkLength() {
    return properties.length > 0;
  }
  function checkFirst() {
    return properties[0] === "write";
  }
  function checkExistence() {
    return properties.every((item) => Object.keys(validOptions).includes(item));
  }
  if (checkLength() && checkExistence() && checkFirst()) {
    return Promise.resolve(getOption(options));
  }
  return Promise.reject(
    "Run 'akuma --help' to see available commands and options"
  );

  // get executable option
  function getOption(options) {
    const keys = Object.keys(options).slice(1);
    return keys.map((key) => [key, options[key]]);
  }
}

(function () {
  const argv = minimist(process.argv.slice(2));
  const handlers = {
    write: generateComment,
  };

  checkValidation(argv)
    .then((res) => {
      if (res[0][0] === "write") {
        handlers.write(res[0][1], res[1] && res[1][1]);
      }
    })
    .catch((err) => console.log(err));
})();
